"""
Wines Management System - SQL Export Utility
Streams SQL DDL schemas, sample datasets, complete database dump,
and table-specific SQL dumps for MySQL Workbench.
"""

import os
from flask import send_file, Response, abort
from config import Config
from db import execute_query

DATABASE_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "database")

def get_sql_file(filename, download_name):
    """Sends static SQL file from database directory."""
    path = os.path.join(DATABASE_DIR, filename)
    if not os.path.exists(path):
        abort(404, description=f"SQL file '{filename}' not found.")
    return send_file(path, as_attachment=True, download_name=download_name, mimetype="application/sql")


def export_table_sql(table_name, download_name):
    """Dynamically generates SQL INSERT statements for any table."""
    rows = execute_query(f"SELECT * FROM {table_name}")
    lines = [
        f"-- ==================================================",
        f"-- SQL Dump for Table: {table_name}",
        f"-- Database: wines_management_db",
        f"-- Generated by Wines Management System",
        f"-- ==================================================",
        f"USE wines_management_db;\n"
    ]

    if not rows:
        lines.append(f"-- No records found in {table_name}.")
    else:
        cols = list(rows[0].keys())
        # In MySQL, subtotal is a STORED GENERATED column in order_details, omit from INSERT
        if table_name == "order_details" and "subtotal" in cols:
            cols.remove("subtotal")

        cols_str = ", ".join(cols)
        lines.append(f"INSERT INTO {table_name} ({cols_str}) VALUES")

        val_rows = []
        for r in rows:
            formatted_vals = []
            for c in cols:
                v = r[c]
                if v is None:
                    formatted_vals.append("NULL")
                elif isinstance(v, (int, float)):
                    formatted_vals.append(str(v))
                else:
                    v_str = str(v).replace("'", "''")
                    formatted_vals.append(f"'{v_str}'")
            val_rows.append(f"({', '.join(formatted_vals)})")

        lines.append(",\n".join(val_rows) + ";\n")

    sql_content = "\n".join(lines)
    return Response(
        sql_content,
        mimetype="application/sql",
        headers={"Content-Disposition": f"attachment; filename={download_name}"}
    )
